services:
  app:
    image: m4nzm333/$APP_NAME:prod
    deploy:
      replicas: $APP_REPLICAS
    env_file: .env
    restart: always
    pull_policy: always
    volumes:
      - lintas-project-data:/var/www/html/storage/app/public
    labels:
      maintainer: m4nzm333
      traefik.enable: true
      traefik.http.routers.$APP_NAME-prod.rule: Host(`$APP_HOSTNAME`)
      traefik.http.routers.$APP_NAME-prod.entrypoints: websecure
      traefik.http.routers.$APP_NAME-prod.tls.certresolver: myresolver
      traefik.http.services.$APP_NAME-prod.loadbalancer.server.port: $APP_PORT
      traefik.http.routers.$APP_NAME-prod.middlewares: scan-banned
      traefik.docker.network: proxy
    networks:
      - proxy
      - lintas-project-net

networks:
  proxy:
    external: true
  lintas-project-net:
    external: true

volumes:
  lintas-project-data:
    name: lintas-project-data
